/**
 * Startup script generation service.
 *
 * Generates executable startup-<mode>.sh scripts that iterate active workspaces
 * and call aerospace-layout-manager for each one.
 *
 * Provides:
 * - generateStartupScript(config, modeName): generate script for a single mode
 * - generateAllStartupScripts(config): generate scripts for all modes
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import type { Config } from '../types.js';
import { resolveMode } from '../routes/modes.js';

// --- Output paths ---

const AEROSPACE_DIR = path.join(os.homedir(), '.config', 'aerospace');
const LAYOUTS_DIR = path.join(AEROSPACE_DIR, 'layouts');

/**
 * Get the startup script path for a mode.
 * Output: ~/.config/aerospace/startup-<mode>.sh
 */
function getStartupScriptPath(modeName: string): string {
  return path.join(AEROSPACE_DIR, `startup-${modeName}.sh`);
}

/**
 * Get the layout JSON path for a workspace in a given mode.
 * - "dual" mode: ~/.config/aerospace/layouts/<ws>.json
 * - "avp" mode: ~/.config/aerospace/layouts/avp/<ws>.json
 * - Other modes: ~/.config/aerospace/layouts/<mode>/<ws>.json
 */
function getLayoutPath(modeName: string, wsName: string): string {
  if (modeName === 'dual') {
    return path.join(LAYOUTS_DIR, `${wsName}.json`);
  }
  return path.join(LAYOUTS_DIR, modeName, `${wsName}.json`);
}

// --- Script generation ---

/**
 * Build the startup script content for a mode.
 * Iterates active workspaces and calls aerospace-layout-manager for each.
 */
function buildStartupScriptContent(
  config: Config,
  modeName: string
): string {
  const resolved = resolveMode(config, modeName);
  if (!resolved) {
    throw new Error(`Mode "${modeName}" not found or cannot be resolved`);
  }

  const lines: string[] = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    `# Generated startup script for mode: ${modeName}`,
    `# Generated at: ${new Date().toISOString()}`,
    '# Do not edit — regenerated by AeroSpace Layout Manager Web UI',
    '',
    'LAYOUT_ENGINE="$HOME/.local/bin/aerospace-layout-manager"',
    '',
  ];

  const activeWorkspaces = Object.entries(resolved)
    .filter(([, ws]) => ws.active)
    .map(([wsName]) => wsName);

  if (activeWorkspaces.length === 0) {
    lines.push('# No active workspaces in this mode');
  } else {
    for (const wsName of activeWorkspaces) {
      const layoutPath = getLayoutPath(modeName, wsName);
      lines.push(`$LAYOUT_ENGINE ${wsName} "${layoutPath}"`);
    }
  }

  lines.push(''); // trailing newline
  return lines.join('\n');
}

// --- Public API ---

export interface StartupScriptResult {
  scriptPath: string;
  activeWorkspaces: string[];
  skippedWorkspaces: string[];
}

/**
 * Generate an executable startup script for a single mode.
 * Writes to ~/.config/aerospace/startup-<mode>.sh with mode 0o755.
 */
export async function generateStartupScript(
  config: Config,
  modeName: string
): Promise<StartupScriptResult> {
  const resolved = resolveMode(config, modeName);
  if (!resolved) {
    throw new Error(`Mode "${modeName}" not found or cannot be resolved`);
  }

  const activeWorkspaces: string[] = [];
  const skippedWorkspaces: string[] = [];

  for (const [wsName, ws] of Object.entries(resolved)) {
    if (ws.active) {
      activeWorkspaces.push(wsName);
    } else {
      skippedWorkspaces.push(wsName);
    }
  }

  const content = buildStartupScriptContent(config, modeName);
  const scriptPath = getStartupScriptPath(modeName);

  // Ensure directory exists
  await fs.mkdir(path.dirname(scriptPath), { recursive: true });

  // Write script and set executable permissions
  await fs.writeFile(scriptPath, content, 'utf-8');
  await fs.chmod(scriptPath, 0o755);

  return { scriptPath, activeWorkspaces, skippedWorkspaces };
}

/**
 * Generate startup scripts for ALL modes in the config.
 */
export async function generateAllStartupScripts(
  config: Config
): Promise<StartupScriptResult[]> {
  const results: StartupScriptResult[] = [];

  for (const modeName of Object.keys(config.modes)) {
    const result = await generateStartupScript(config, modeName);
    results.push(result);
  }

  return results;
}
